# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Seed Activities
Activity.create(activity_name: 'Cycling')
Activity.create(activity_name: 'Stair Stepper')
Activity.create(activity_name: 'HIIT')
Activity.create(activity_name: 'Yoga')
Activity.create(activity_name: 'Strength Training')
Activity.create(activity_name: 'Core Training')
Activity.create(activity_name: 'Pilates')
Activity.create(activity_name: 'Swimming')
Activity.create(activity_name: 'Kickboxing')
Activity.create(activity_name: 'Boxing')
Activity.create(activity_name: 'Soccer')
Activity.create(activity_name: 'Basketball')
Activity.create(activity_name: 'Rock Climbing')
Activity.create(activity_name: 'Badminton')
Activity.create(activity_name: 'Ice Skating')
Activity.create(activity_name: 'Skating')
Activity.create(activity_name: 'Ping Pong')
Activity.create(activity_name: 'Walking')
Activity.create(activity_name: 'Running')
Activity.create(activity_name: 'Rowing')
Activity.create(activity_name: 'Cross Country Skiing')
Activity.create(activity_name: 'Snowboarding')
Activity.create(activity_name: 'Skiing')
Activity.create(activity_name: 'Dancing')
Activity.create(activity_name: 'Gymnastics')
Activity.create(activity_name: 'Martial Arts')
Activity.create(activity_name: 'Fencing')
Activity.create(activity_name: 'Golf')
Activity.create(activity_name: 'Tennis')
Activity.create(activity_name: 'Table Tennis')
Activity.create(activity_name: 'Volleyball')
Activity.create(activity_name: 'Handball')
Activity.create(activity_name: 'Rugby')
Activity.create(activity_name: 'American Football')
Activity.create(activity_name: 'Cricket')
Activity.create(activity_name: 'Hockey')
Activity.create(activity_name: 'Field Hockey')
Activity.create(activity_name: 'Lacrosse')
Activity.create(activity_name: 'Archery')
Activity.create(activity_name: 'Bowling')
Activity.create(activity_name: 'Squash')
Activity.create(activity_name: 'Racquetball')
Activity.create(activity_name: 'Surfing')
Activity.create(activity_name: 'Windsurfing')
Activity.create(activity_name: 'Kitesurfing')
Activity.create(activity_name: 'Paragliding')
Activity.create(activity_name: 'Skydiving')
Activity.create(activity_name: 'Bungee Jumping')
Activity.create(activity_name: 'Horseback Riding')
Activity.create(activity_name: 'Climbing')
Activity.create(activity_name: 'Hiking')
Activity.create(activity_name: 'Trail Running')
Activity.create(activity_name: 'Mountain Biking')
Activity.create(activity_name: 'BMX')
Activity.create(activity_name: 'Skateboarding')
Activity.create(activity_name: 'Scuba Diving')
Activity.create(activity_name: 'Snorkeling')
Activity.create(activity_name: 'Kayaking')
Activity.create(activity_name: 'Canoeing')
Activity.create(activity_name: 'Stand Up Paddleboarding')
Activity.create(activity_name: 'Fishing')
Activity.create(activity_name: 'Spearfishing')
Activity.create(activity_name: 'Paintball')
Activity.create(activity_name: 'Laser Tag')
Activity.create(activity_name: 'Chess')
Activity.create(activity_name: 'Equestrian')
Activity.create(activity_name: 'Polo')
Activity.create(activity_name: 'Dodgeball')
Activity.create(activity_name: 'Ultimate Frisbee')
Activity.create(activity_name: 'Aerobics')
Activity.create(activity_name: 'Barre')
Activity.create(activity_name: 'Zumba')
Activity.create(activity_name: 'Spinning')
Activity.create(activity_name: 'Capoeira')
Activity.create(activity_name: 'Parkour')
Activity.create(activity_name: 'Sailing')
Activity.create(activity_name: 'Triathlon Training')
Activity.create(activity_name: 'Biathlon')
Activity.create(activity_name: 'Decathlon')
Activity.create(activity_name: 'Heptathlon')
Activity.create(activity_name: 'Pentathlon')
Activity.create(activity_name: 'Javelin Throw')
Activity.create(activity_name: 'Hammer Throw')
Activity.create(activity_name: 'Discus Throw')
Activity.create(activity_name: 'Shot Put')
Activity.create(activity_name: 'High Jump')
Activity.create(activity_name: 'Long Jump')
Activity.create(activity_name: 'Triple Jump')
Activity.create(activity_name: 'Pole Vault')
Activity.create(activity_name: 'Synchronized Swimming')
Activity.create(activity_name: 'Water Polo')
Activity.create(activity_name: 'Diving')
Activity.create(activity_name: 'Rhythmic Gymnastics')
Activity.create(activity_name: 'Trampoline')
Activity.create(activity_name: 'Powerlifting')
Activity.create(activity_name: 'Bodybuilding')
Activity.create(activity_name: 'CrossFit')
Activity.create(activity_name: 'Calisthenics')
Activity.create(activity_name: 'Piloxing')
Activity.create(activity_name: 'Krav Maga')
Activity.create(activity_name: 'Taekwondo')
Activity.create(activity_name: 'Judo')
Activity.create(activity_name: 'Karate')
Activity.create(activity_name: 'Aikido')
Activity.create(activity_name: 'Brazilian Jiu-Jitsu')
Activity.create(activity_name: 'Muay Thai')
Activity.create(activity_name: 'Wrestling')
Activity.create(activity_name: 'Sumo Wrestling')
Activity.create(activity_name: 'Kendo')
Activity.create(activity_name: 'Frisbee')
Activity.create(activity_name: 'Speed Skating')
Activity.create(activity_name: 'Short Track Speed Skating')
Activity.create(activity_name: 'Curling')
Activity.create(activity_name: 'Bobsleigh')
Activity.create(activity_name: 'Skeleton')
Activity.create(activity_name: 'Luge')
Activity.create(activity_name: 'Snowshoeing')
Activity.create(activity_name: 'Biathlon')
Activity.create(activity_name: 'Nordic Combined')
Activity.create(activity_name: 'Snow Kiting')
Activity.create(activity_name: 'Ice Hockey')
Activity.create(activity_name: 'Figure Skating')
Activity.create(activity_name: 'Speedminton')
Activity.create(activity_name: 'Softball')
Activity.create(activity_name: 'Baseball')
Activity.create(activity_name: 'Beach Volleyball')
Activity.create(activity_name: 'Beach Soccer')
Activity.create(activity_name: 'Sandboarding')
Activity.create(activity_name: 'Mountain Boarding')
Activity.create(activity_name: 'Orienteering')
Activity.create(activity_name: 'Adventure Racing')
Activity.create(activity_name: 'Geocaching')
Activity.create(activity_name: 'Bird Watching')
Activity.create(activity_name: 'Star Gazing')
Activity.create(activity_name: 'Hot Air Ballooning')
Activity.create(activity_name: 'Gliding')
Activity.create(activity_name: 'Flying')
Activity.create(activity_name: 'Hang Gliding')
Activity.create(activity_name: 'Ballooning')
Activity.create(activity_name: 'Jet Skiing')
Activity.create(activity_name: 'Water Skiing')
Activity.create(activity_name: 'Wakeboarding')
Activity.create(activity_name: 'Bodyboarding')
Activity.create(activity_name: 'Rafting')
Activity.create(activity_name: 'Canyoning')
Activity.create(activity_name: 'Caving')
Activity.create(activity_name: 'Rock Scrambling')
Activity.create(activity_name: 'Mountaineering')
Activity.create(activity_name: 'Backpacking')
Activity.create(activity_name: 'Camping')
Activity.create(activity_name: 'RVing')
Activity.create(activity_name: 'Yachting')

Gym.create(name: 'Polo Gym')
Gym.create(name: 'Rec center')
Gym.create(name: 'Westside Gym')
Gym.create(name: 'Orange Fitness')
Gym.create(name: 'YMCA')
Gym.create(name: '24-Hour Fitness')
