class UpdateGymAndActivityLists < ActiveRecord::Migration[7.0]
  def change
    ActivityPreference.delete_all
    Activity.delete_all
    Gym.delete_all

    activities = [
      "Aerobics",
      "Archery",
      "Badminton",
      "Ballet",
      "Baseball",
      "Basketball",
      "Baton twirling",
      "Biathlon",
      "Bicycling",
      "Bodybuilding",
      "Bowling",
      "Boxing",
      "Calisthenics",
      "Canoeing",
      "Cheerleading",
      "Circuit training",
      "Climbing",
      "Cricket",
      "Croquet",
      "Cross-country skiing",
      "Curling",
      "Cycling",
      "Dance (various forms)",
      "Darts",
      "Diving",
      "Dodgeball",
      "Fencing",
      "Field hockey",
      "Figure skating",
      "Fishing",
      "Flag football",
      "Football (American)",
      "Football (soccer)",
      "Frisbee",
      "Golf",
      "Gymnastics",
      "Handball",
      "Hang gliding",
      "High-intensity interval training (HIIT)",
      "Hiking",
      "Hockey (field, ice, roller)",
      "Horseback riding",
      "Hurling",
      "Ice skating",
      "Inline skating",
      "Jai alai",
      "Javelin throw",
      "Judo",
      "Juggling",
      "Jumping rope",
      "Karate",
      "Kayaking",
      "Kickball",
      "Kickboxing",
      "Kite surfing",
      "Lacrosse",
      "Lawn bowling",
      "Martial arts",
      "Mixed martial arts (MMA)",
      "Mountaineering",
      "Netball",
      "Nordic walking",
      "Orienteering",
      "Paddleboarding",
      "Parkour",
      "Petanque",
      "Pickleball",
      "Pilates",
      "Ping pong (table tennis)",
      "Polo",
      "Powerlifting",
      "Qigong",
      "Racquetball",
      "Rafting",
      "Rock climbing",
      "Roller skating",
      "Rowing",
      "Rugby",
      "Running",
      "Sailing",
      "Scuba diving",
      "Sepak takraw",
      "Skateboarding",
      "Skiing (alpine, cross-country, water)",
      "Skydiving",
      "Snorkeling",
      "Snowboarding",
      "Snowshoeing",
      "Softball",
      "Speed skating",
      "Squash",
      "Standup paddleboarding",
      "Surfing",
      "Swimming",
      "Synchronized swimming",
      "Table tennis",
      "Taekwondo",
      "Tai chi",
      "Tennis",
      "Trampoline",
      "Triathlon",
      "Ultimate frisbee",
      "Volleyball (indoor, beach)",
      "Wakeboarding",
      "Walking",
      "Water aerobics",
      "Water polo",
      "Weightlifting",
      "Windsurfing",
      "Wrestling",
      "Yoga",
      "Zumba"
    ]

    gyms = [
      "Student Recreation Center",
      "Southside Recreation Center",
      "Polo Recreation Center",
      "Penberthy Rec Sports Complex",
      "Physical Education Activity Building (PEAP)",
      "Omar Smith Instructional Tennis Center",
      "Off Campus"
    ]

    activities.each do |activity_name|
      Activity.create(activity_name: activity_name)
    end

    gyms.each do |gym_name|
      Gym.create(name: gym_name)
    end
  end
end
